### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by randoomdude** [mtamc/masterduel_readability#1]
Any possibility for masterduelmeta style green/red highlights for activation/condition? Also would be nice if the card format only affected the effect windows and not the raw card which just looks out of place with the text overflowing past the border
![image](https://github.com/mtamc/masterduel_readability/assets/6027132/acc11af5-949f-46f4-a9ef-116f8d445c6e)

**Comment by mtamc** [comment]
Sorry late reply. according to my RndUser0 coloring or highlighting text is not possible.
I don't know how to not affect the raw card unfortunately
